# services:
#   db:
#     image: postgres:16
#     restart: always
#     environment:
#       POSTGRES_USER: prasad
#       POSTGRES_PASSWORD: YourStrongPass123!
#       POSTGRES_DB: nexusdb
#     ports:
#       - "5433:5432"
#     volumes:
#       - postgres_data:/var/lib/postgresql/data

#   web:
#     build: .
#     command: python run.py
#     volumes:
#       - .:/app
#     ports:
#       - "5433:5432"
#     environment:
#       - DATABASE_URL=postgresql+psycopg://sonar:sonar123@43.204.3.223:5432/postgres
#     depends_on:
#       - db

#   pgadmin:
#     image: dpage/pgadmin4
#     restart: always
#     environment:
#       PGADMIN_DEFAULT_EMAIL: admin@admin.com
#       PGADMIN_DEFAULT_PASSWORD: admin
#     ports:
#       - "5050:80"
#     depends_on:
#       - db
#     volumes:
#       - pgadmin_data:/var/lib/pgadmin

# volumes:
#   postgres_data:
#   pgadmin_data:   # ✅ Add this line


# # to run docker compose up --build

services:
  web:
    build: .
    command: python run.py
    volumes:
      - .:/app
    ports:
      - "5001:5000"
    environment:
      # - DATABASE_URL=postgresql+psycopg://sonar:sonar123@43.204.3.223:5432/postgres
      # - REDIS_URL=redis://default:vmVLEc2mvOk5VlB1ZDyGgCuJ81SmpCP5@redis-14311.crce206.ap-south-1-1.ec2.redns.redis-cloud.com:14311
      # - OPENROUTER_API_KEY=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

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  pgadmin_data:
