name: Build and Push Docker Images

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 4: Build and push Backend image (multi-arch)
      - name: Build and Push Backend image
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            -t sureshnangina/backend:latest \
            --push \
            ./server

      # Step 5: Build and push Frontend image (multi-arch)
      - name: Build and Push Frontend image
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            -t sureshnangina/frontend:latest \
            --push \
            ./client
